version: '3.8'
services:
  apache:
    build: apache
    ports:
      - "80:80"
    volumes:
      - /var/www/:/var/www/
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mariadb:/var/lib/mysql